apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-httpd1
  name: test-httpd1
  namespace: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-httpd1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-httpd1
    spec:
      containers:
      - image: quay.apps.cluster-n7lqw.n7lqw.sandbox234.opentlc.com/test-organization/test-repo:httpd-v1
        imagePullPolicy: IfNotPresent
        name: test-repo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: httpd1
      serviceAccountName: httpd1
      terminationGracePeriodSeconds: 30
