apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: devsecops-pipeline
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd
  sessionAffinity: None
  type: ClusterIP
